#!/usr/bin/env bash
set -e;

apt-get update
until apt-get install --download-only -y $(cat /etc/apt/packages.list); do
    echo "apt install failed. Likely throttled. Retrying in 10 mins...";
    sleep 600;
done;

(
	cd /var/cache/apt/archives \
		&& find . -type f \( -iname \*.deb \) -exec sha256sum {} \; \
		| sed 's/.\///g' \
		| LC_ALL=C sort
) > /etc/apt/package-hashes-compare.txt

diff /etc/apt/package-hashes{,-compare}.txt

apt-get install -y $(cat /etc/apt/packages.list)

rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*;
