#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; source environment

build_dir="${BUILD_DIR?}"
buildroot_dir="${build_dir}/buildroot"

(cd "${buildroot_dir}"; make )
