#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; source environment

devices=${DEVICES?}
build_dir="${BUILD_DIR?}"
heads_dir="${build_dir}/heads"

for device in ${devices}; do
	(cd "${heads_dir}"; make BOARD="$device")
done
