#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; source environment

build_dir="${BUILD_DIR?}"
release_dir="${RELEASE_DIR?}"

[ -d "${build_dir}/buildroot" ] && (cd ${build_dir}/buildroot && make clean)
[ -d "${build_dir}/heads" ] && (cd ${build_dir}/heads && make real.clean)
[ -d "${build_dir}/buildroot-ccache" ] && rm -rf ${build_dir}/buildroot-ccache
[ -d "${release_dir}" ] && rm -rf ${release_dir}/develop
