#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; source environment

build_dir="${BUILD_DIR?}"
release_dir="${RELEASE_DIR?}"

[ -d "${build_dir}" ] && rm -rf ${build_dir}/*
[ -d "${release_dir}" ] && rm -rf ${release_dir}/*
