#!/bin/bash

target=${TARGET?}
env_file=${HOME}/config/config.env

[ -f $env_file ] && export $( cat ${env_file} | xargs )

export BUILD_DIR="${HOME}/build"
export BR2_EXTERNAL="${HOME}/config/buildroot"
export RELEASE_DIR="${HOME}/release"
export BUILDROOT_REPO=git://git.busybox.net/buildroot
export HEADS_REPO=https://source.puri.sm/coreboot/purism-heads.git
export FAKETIME="@${GIT_DATETIME?}"
export SOURCE_DATE_EPOCH="${GIT_EPOCH?}"
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
export ROOTFS_ISO9660_GENISOIMAGE_OPTS="-creation-date=${GIT_EPOCH} "
