#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
set -e; source environment

target=${TARGET?}

cd /home/build/buildroot
make "airgap_${TARGET}_defconfig"
make menuconfig
