#!/bin/bash
[ -f /.dockerenv ] || { echo "please run in supplied container"; exit 1; }
source environment
set -e

qemu-system-i386 \
	-M pc \
	-nographic \
	-append "console=ttyS0" \
	-kernel "$HOME/release/bzImage"
