#!/usr/bin/env bash
set -e;

ARCH=$(uname -m)

cp /config/toolchain/* /etc/apt/

apt-get update
apt-get install debian-archive-keyring

until apt-get install --download-only --reinstall --allow-downgrades -y $(cat /etc/apt/packages-${ARCH}.list); do
    echo "apt install failed. Likely throttled. Retrying in 10 mins...";
    sleep 600;
done;

(
	cd /var/cache/apt/archives \
		&& find . -type f \( -iname \*.deb \) -exec sha256sum {} \; \
		| sed 's/.\///g' \
		| LC_ALL=C sort
) > /etc/apt/package-hashes-${ARCH}-compare.txt

diff /etc/apt/package-hashes-${ARCH}{,-compare}.txt

apt-get install --allow-downgrades -y $(cat /etc/apt/packages-${ARCH}.list)
rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* /tmp/* /var/tmp/*;
